name: Update Gallery

on:
  push:
    branches:
      - main
    paths-ignore:
      - "gallery-images.js"

permissions:
  contents: write

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Generate gallery-images.js
        run: |
          python - <<'PY'
          import os

          extensions = (
              ".jpg",
              ".jpeg",
              ".png",
              ".gif",
              ".webp",
              ".bmp"
          )

          images = []

          for filename in os.listdir("."):
              if filename.lower().endswith(extensions):
                  images.append(filename)

          images.sort()

          with open("gallery-images.js", "w", encoding="utf-8") as f:
              f.write("const images = [\n")

              for image in images:
                  f.write("    " + repr(image) + ",\n")

              f.write("];\n")

          print("Gallery updated!")
          print(images)
          PY

      - name: Save gallery-images.js
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add gallery-images.js

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update gallery"
            git push
          fi
